from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path
from zoneinfo import ZoneInfo


ACCOUNT_RE = re.compile(r"^\s*\d{4}-\d{2}-\d{2}\s+open\s+([A-Z][A-Za-z0-9:-]+)")


@dataclass(frozen=True)
class Posting:
    account: str
    amount: Decimal
    currency: str


@dataclass(frozen=True)
class Transaction:
    date: date
    payee: str
    narration: str
    postings: tuple[Posting, ...]
    metadata: dict[str, str]


class LedgerError(RuntimeError):
    pass


@dataclass(frozen=True)
class LedgerEntry:
    path: Path
    index: int
    text: str
    date: str
    payee: str
    narration: str
    amount: str | None


ENTRY_HEADER_RE = re.compile(
    r'^(?P<date>\d{4}-\d{2}-\d{2})\s+[*!]\s+"(?P<payee>(?:[^"\\]|\\.)*)"\s+"(?P<narration>(?:[^"\\]|\\.)*)"'
)
ENTRY_START_RE = re.compile(r"^\d{4}-\d{2}-\d{2}\s+[*!]\s+")
POSTING_AMOUNT_RE = re.compile(r"\s(?P<amount>-?\d+(?:\.\d+)?)\s+[A-Z][A-Z0-9_]*\s*$")


def parse_amount(value: str) -> Decimal:
    normalized = value.strip().replace(",", "")
    try:
        amount = Decimal(normalized)
    except InvalidOperation as exc:
        raise ValueError("金额格式不正确") from exc
    if amount <= 0:
        raise ValueError("金额必须大于 0")
    return amount


def decimal_text(value: Decimal) -> str:
    text = format(value.normalize(), "f")
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return text


def quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_transaction(tx: Transaction) -> str:
    lines = [f'{tx.date.isoformat()} * "{quote(tx.payee)}" "{quote(tx.narration)}"']
    for key, value in tx.metadata.items():
        lines.append(f'  {key}: "{quote(value)}"')
    for posting in tx.postings:
        lines.append(
            f"  {posting.account:<56} {decimal_text(posting.amount)} {posting.currency}"
        )
    return "\n".join(lines) + "\n"


def make_expense(
    *,
    tx_date: date,
    amount: Decimal,
    payee: str,
    narration: str,
    source_account: str,
    expense_account: str,
    currency: str,
    metadata: dict[str, str],
    discount_amount: Decimal | None = None,
    discount_account: str = "Income:Discount",
) -> Transaction:
    postings = [
        Posting(source_account, -amount, currency),
        Posting(expense_account, amount, currency),
    ]
    if discount_amount:
        postings[1] = Posting(expense_account, amount + discount_amount, currency)
        postings.append(Posting(discount_account, -discount_amount, currency))

    return Transaction(
        date=tx_date,
        payee=payee,
        narration=narration,
        postings=tuple(postings),
        metadata=metadata,
    )


def make_income(
    *,
    tx_date: date,
    amount: Decimal,
    payee: str,
    narration: str,
    target_account: str,
    income_account: str,
    currency: str,
    metadata: dict[str, str],
) -> Transaction:
    return Transaction(
        date=tx_date,
        payee=payee,
        narration=narration,
        postings=(
            Posting(target_account, amount, currency),
            Posting(income_account, -amount, currency),
        ),
        metadata=metadata,
    )


def make_transfer(
    *,
    tx_date: date,
    amount: Decimal,
    payee: str,
    narration: str,
    from_account: str,
    to_account: str,
    currency: str,
    metadata: dict[str, str],
) -> Transaction:
    return Transaction(
        date=tx_date,
        payee=payee,
        narration=narration,
        postings=(
            Posting(from_account, -amount, currency),
            Posting(to_account, amount, currency),
        ),
        metadata=metadata,
    )


def load_accounts(root: Path) -> list[str]:
    accounts: set[str] = set()
    for path in root.rglob("*.bean"):
        for line in path.read_text(encoding="utf-8").splitlines():
            match = ACCOUNT_RE.match(line)
            if match:
                accounts.add(match.group(1))
    return sorted(accounts)


def filter_accounts(accounts: list[str], prefixes: tuple[str, ...]) -> list[str]:
    return [account for account in accounts if account.startswith(prefixes)]


def output_path(output_dir: Path, tx_date: date) -> Path:
    return output_dir / f"{tx_date:%Y}" / f"{tx_date:%m}.bean"


def append_transaction(
    *,
    output_dir: Path,
    beancount_file: Path,
    tx: Transaction,
) -> Path:
    path = output_path(output_dir, tx.date)
    path.parent.mkdir(parents=True, exist_ok=True)
    previous = path.read_text(encoding="utf-8") if path.exists() else None
    created = previous is None

    header = ""
    if created:
        header = "; Generated by Telegram bot. Edit only if manual correction is needed.\n\n"

    entry = render_transaction(tx)
    with path.open("a", encoding="utf-8") as handle:
        if header:
            handle.write(header)
        elif path.stat().st_size > 0:
            handle.write("\n")
        handle.write(entry)

    try:
        check_ledger(beancount_file)
    except Exception:
        if created:
            path.unlink(missing_ok=True)
        else:
            path.write_text(previous, encoding="utf-8")
        raise

    return path


def list_recent_entries(output_dir: Path, limit: int = 5) -> list[LedgerEntry]:
    entries: list[LedgerEntry] = []
    for path in iter_entry_files(output_dir):
        entries.extend(parse_ledger_entries(path))
    return sorted(entries, key=entry_sort_key, reverse=True)[:limit]


def iter_entry_files(output_dir: Path) -> list[Path]:
    return [
        path
        for path in output_dir.rglob("*.bean")
        if path.name != "main.bean"
    ]


def parse_ledger_entries(path: Path) -> list[LedgerEntry]:
    lines = path.read_text(encoding="utf-8").splitlines()
    starts = [index for index, line in enumerate(lines) if ENTRY_START_RE.match(line)]
    entries: list[LedgerEntry] = []
    for entry_index, start in enumerate(starts):
        end = starts[entry_index + 1] if entry_index + 1 < len(starts) else len(lines)
        text = "\n".join(lines[start:end]).rstrip()
        header = ENTRY_HEADER_RE.match(lines[start])
        if not header:
            continue
        entries.append(
            LedgerEntry(
                path=path,
                index=entry_index,
                text=text,
                date=header.group("date"),
                payee=unquote(header.group("payee")),
                narration=unquote(header.group("narration")),
                amount=extract_entry_amount(text),
            )
        )
    return entries


def entry_sort_key(entry: LedgerEntry) -> tuple[int, int, int, str]:
    year, month = entry_file_sort_key(entry.path)
    return (year, month, entry.index, str(entry.path))


def entry_file_sort_key(path: Path) -> tuple[int, int]:
    parent = path.parent.name
    stem = path.stem
    if parent.isdigit() and len(parent) == 4 and stem.isdigit() and len(stem) == 2:
        return (int(parent), int(stem))

    match = re.match(r"^(\d{4})-(\d{2})$", stem)
    if match:
        return (int(match.group(1)), int(match.group(2)))

    return (0, 0)


def delete_entry(entry: LedgerEntry, beancount_file: Path) -> None:
    previous = entry.path.read_text(encoding="utf-8")
    updated = remove_entry(previous, entry)
    entry.path.write_text(updated, encoding="utf-8")
    try:
        check_ledger(beancount_file)
    except Exception:
        entry.path.write_text(previous, encoding="utf-8")
        raise


def remove_entry(content: str, entry: LedgerEntry) -> str:
    if entry.index >= 0:
        lines = content.splitlines()
        starts = [index for index, line in enumerate(lines) if ENTRY_START_RE.match(line)]
        if entry.index < len(starts):
            start = starts[entry.index]
            end = starts[entry.index + 1] if entry.index + 1 < len(starts) else len(lines)
            current = "\n".join(lines[start:end]).rstrip()
            if current == entry.text.rstrip():
                del lines[start:end]
                return normalize_entry_spacing("\n".join(lines))
    return remove_entry_text(content, entry.text)


def remove_entry_text(content: str, entry_text: str) -> str:
    normalized_entry = entry_text.rstrip()
    lines = content.splitlines()
    starts = [index for index, line in enumerate(lines) if ENTRY_START_RE.match(line)]
    for entry_index, start in enumerate(starts):
        end = starts[entry_index + 1] if entry_index + 1 < len(starts) else len(lines)
        current = "\n".join(lines[start:end]).rstrip()
        if current == normalized_entry:
            del lines[start:end]
            return normalize_entry_spacing("\n".join(lines))
    raise LedgerError("entry not found")


def normalize_entry_spacing(content: str) -> str:
    stripped = content.rstrip()
    return stripped + "\n" if stripped else ""


def extract_entry_amount(text: str) -> str | None:
    for line in text.splitlines():
        match = POSTING_AMOUNT_RE.search(line)
        if match and not match.group("amount").startswith("-"):
            return match.group("amount")
    return None


def unquote(value: str) -> str:
    return value.replace('\\"', '"').replace("\\\\", "\\")


def check_ledger(beancount_file: Path) -> None:
    result = subprocess.run(
        ["bean-check", str(beancount_file)],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        raise LedgerError(detail or "bean-check failed")


def default_metadata(timezone: ZoneInfo) -> dict[str, str]:
    return {
        "source": "telegram",
        "created_at": datetime.now(timezone).strftime("%Y-%m-%d %H:%M:%S"),
    }
